echo "Uninstalling Bomberman..."
rm -rf Bomberman
rm -rf CMakeCache.txt
rm -rf CMakeFiles
rm -rf Makefile
rm -rf cmake_install.cmake
rm -rf config.init
rm -rf Libs/nanogui
echo "Uninstalled Succesfully!"
